repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-merge-conflict

- repo: local
  hooks:
  - id: black
    name: black
    description: "Python formatter"
    stages: ["pre-commit", "pre-push"]
    entry: "black"
    language: system
    'types': [file, python]
  - id: ripsecrets
    name: ripsecrets
    description: "Check when publishing secrets"
    stages: ["pre-commit", "pre-push"]
    'types': [text]
    require_serial: true
    entry: "ripsecrets --strict-ignore"
    language: system
  - id: taplo
    name: taplo
    description: "TOML formatter"
    stages: ["pre-commit", "pre-push"]
    entry: "taplo fmt"
    language: system
    'types': [file, toml]
  - id: typos
    name: typos
    description: "Check typos in the code"
    stages: ["pre-commit", "pre-push"]
    entry: "typos --config typos.toml --format brief --write-changes"
    language: system
    'types': [text]
  - id: cargo-fmt
    name: cargo fmt
    description: "Format rust files with cargo fmt"
    stages: ["pre-commit", "pre-push"]
    entry: "cargo fmt --all"
    language: system
    'types': [file, rust]
    require_serial: true
    pass_filenames: false
    fail_fast: true
  - id: cargo-clippy
    name: cargo clippy
    description: "Run cargo clippy lint tool"
    stages: ["pre-commit", "pre-push"]
    entry: "env CUDARC_CUDA_VERSION=13000 cargo clippy --workspace --all-targets --all-features -- -D warnings"
    language: system
    'types': [file, rust]
    require_serial: true
    pass_filenames: false
    fail_fast: true
  - id: cargo-check
    name: cargo check
    description: "Run cargo check for compilation errors"
    stages: ["pre-commit", "pre-push"]
    entry: "cargo check"
    language: system
    'types': [file, rust]
    require_serial: true
    pass_filenames: false
    fail_fast: true
