[workspace]
members = ["zkml", "deep-prove", "utils", "tenvis", "telemetry"]
resolver = "2"

[workspace.package]
categories = ["cryptography", "zk", "blockchain"]
edition = "2021"
keywords = ["cryptography", "zk", "blockchain"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/LagrangeLabs/deep-prove"
version = "1.0.1"

[workspace.dependencies]
anyhow = { version = "1.0", default-features = false }
ark-std = "0.5"
aws-config = { version = "1.8", features = ["behavior-version-latest"] }
aws-sdk-marketplacemetering = "1.78"
axum = { version = "0.8" }
bincode = { version = "2.0.1" }
clap = "4"
compact_str = "0.9"
csv = "1.3.1"
derive_more = "2.0.1"
either = "1.15"
hex = { version = "0.4" }
itertools = "0.13"
memmap2 = "0.9"
object_store = { version = "0.12", features = ["aws"] }
p3-field = { git = "https://github.com/Plonky3/Plonky3", rev = "539bbc84085efb609f4f62cb03cf49588388abdb" }
p3-goldilocks = { git = "https://github.com/Plonky3/Plonky3", rev = "539bbc84085efb609f4f62cb03cf49588388abdb", features = [
  "nightly-features",
] }
rayon = "1.10"
rmp-serde = "1.3.0"
semver = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3"
thiserror = "2.0.12"
timed = { git = "https://github.com/nikkolasg/timed-rs" }
timed-core = { git = "https://github.com/nikkolasg/timed-rs" }
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tract-onnx = "0.21"
ureq = { version = "3.1.2", features = ["default", "json"] }

ceno-p3 = { package = "p3", git = "https://github.com/Lagrange-Labs/gkr-backend", branch = "deep-prove-extra-features" }
ff_ext = { git = "https://github.com/Lagrange-Labs/gkr-backend", branch = "deep-prove-extra-features" }
mpcs = { package = "mpcs", git = "https://github.com/Lagrange-Labs/gkr-backend", branch = "deep-prove-extra-features" }
multilinear_extensions = { git = "https://github.com/Lagrange-Labs/gkr-backend", branch = "deep-prove-extra-features" }
sumcheck = { git = "https://github.com/Lagrange-Labs/gkr-backend", branch = "deep-prove-extra-features" }
transcript = { git = "https://github.com/Lagrange-Labs/gkr-backend", branch = "deep-prove-extra-features" }
witness = { package = "witness", git = "https://github.com/Lagrange-Labs/gkr-backend", branch = "deep-prove-extra-features" }

# Test must run fast, but still provides stacktraces.
[profile.test]
debug = true
debug-assertions = true
opt-level = 3
overflow-checks = true

[profile.test.package."*"]
opt-level = 3

[profile.release]
debug = 1
debug-assertions = true
# LTO, even thin, is **very slow** to compile for marginal gains at best
lto = "off"

[profile.fast]
inherits = "release"
lto = "fat"

#[patch."https://github.com/nikkolasg/timed-rs"]
#timed = { path = "/Users/nalos/prog/timed/timed" }
#timed-core = { path = "/Users/nalos/prog/timed/timed-core" }

[workspace.metadata.release]
pre-release-hook = ["sh", "../.github/changelog.sh"]
publish = false
