[files]
extend-exclude = ["*.nix"]

[default]
check-filename = true
extend-identifiers = { "Ein" = "Ein", "EinSum" = "EinSum", "NdArray" = "NdArray" }
format = "brief"

[default.extend-words]
Ein = "Ein"
arange = "arange"
