[package]
name = "tenstore"
description = "a facade to store & retrieve stored pages"
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
remote-store.workspace = true
anyhow.workspace = true
rmp-serde.workspace = true
serde.workspace = true
tempfile.workspace = true
thiserror.workspace = true
uuid.workspace = true
weight-lru = "0.0.3"

[dev-dependencies]
tokio.workspace = true
test-log.workspace = true
