[features]
otel = ["telemetry/otel"]

[package]
name = "tenstore"
description = "a facade to store & retrieve stored pages"
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
exponential-backoff.workspace = true
reqwest = { version = "0.13.1", features = ["json"] }
rmp-serde.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10.9"
telemetry = { package = "telemetry", path = "../telemetry" }
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["tracing", "macros"] }
tokio-metrics.workspace = true
tracing.workspace = true
url.workspace = true
urlencoding = "2.1"
uuid = { workspace = true, features = ["serde", "v5"] }
vise.workspace = true
weight-lru = "0.0.3"
zstd = "0.13.3"

[dev-dependencies]
test-log.workspace = true
tokio.workspace = true
