use ark_ff::PrimeField;
use itertools::Itertools;
use serde::{Deserialize, Serialize};

/// An evaluation of an polynomial, altogether with the number of variables.
/// This data can be used by the verifier to reconstruct a specific claim about
/// the polynomial itself
#[derive(Clone, Debug, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(bound(
    serialize = "F: ark_serialize::CanonicalSerialize",
    deserialize = "F: ark_serialize::CanonicalDeserialize"
))]
pub(crate) struct PolynomialEvaluation<F> {
    pub(crate) num_vars: usize,
    #[serde(with = "dp_crypto::serialization")]
    pub(crate) eval: F,
}

/// Claim type to accumulate in this protocol, for a certain polynomial, known in the context.
/// f(point) = eval
#[derive(Clone, Debug, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(bound(
    serialize = "F: ark_serialize::CanonicalSerialize",
    deserialize = "F: ark_serialize::CanonicalDeserialize"
))]
pub struct Claim<F> {
    #[serde(with = "dp_crypto::serialization")]
    pub point: Vec<F>,
    #[serde(with = "dp_crypto::serialization")]
    pub eval: F,
}

impl<F> Claim<F> {
    pub fn new(point: Vec<F>, eval: F) -> Self {
        Self { point, eval }
    }
    pub fn mle_num_vars(&self) -> usize {
        self.point.len()
    }

    pub fn point(&self) -> &[F] {
        &self.point
    }
}

impl<F: PrimeField> Claim<F> {
    /// Pad the point to the new size given
    /// This is necessary for passing from output of padded lookups to next dense layer proving for example.
    /// NOTE: you can use it to pad or reduce size
    pub fn pad(&self, new_num_vars: usize) -> Claim<F> {
        Self {
            eval: self.eval,
            point: self
                .point
                .iter()
                .chain(std::iter::repeat(&F::ZERO))
                .take(new_num_vars)
                .cloned()
                .collect_vec(),
        }
    }

    pub fn evaluation(&self) -> F {
        self.eval
    }
}
// TODO: move to this register as code is repeating the same piece of code everytime
// pub struct ClaimRegister<E> {
//    intra_nodes: HashMap<NodeID, Vec<Claim<E>>>,
//    output_claims: Vec<Claim<E>>,
//}
// impl<E: ExtensionField> ClaimRegister<E> {
//    pub fn new() -> Self {
//        Self {
//            intra_nodes: HashMap::new(),
//            output_claims: Vec::new(),
//        }
//    }
//
//    /// for every port link in this edge, store the claim to the corresponding claim store
//    /// Each claim is generated by a layer and it corresponds to an edge + port link.
//    pub fn store_claims_from_edge(&mut self, claim: &[Claim<E>], edge: ModelEdge) -> anyhow::Result<()> {
//        let expected_num_output = edge.ports().iter().count();
//        ensure!(expected_num_output == claim.len(), "Number of claims and expected number of outputs must be the same");
//        for port in edge.ports().iter() {
//            match edge.target() {
//                Target::Node(node) => {
//                    // since we prove in reverse, it's always the source port that receives the claim
//                    self.intra_nodes.entry(*node).or_default().push(claim[usize::from(port.source_port)].clone());
//                }
//                Target::Output => {
//                    self.output_claims.push(claim[usize::from(port.source_port)].clone());
//                }
//            }
//        }
//        Ok(())
//    }
//}
