use crate::{
    Claim, Tensor, VectorTranscript,
    graph::NodeOutput,
    iop::{chunking::ChunkIOCommitments, claim::PolynomialEvaluation},
    lookup::context::LookupContext,
};
use std::collections::{BTreeMap, HashMap};

use crate::{
    commit::mmcs_context::ModelOpeningProof,
    graph::NodeId,
    iop::{chunking::ModelChunk, prover::MergeClaimsProof},
    layers::LayerProof,
    lookup::logup_gkr::structs::LogUpBatchProof,
};
use ff_ext::ExtensionField;
use mpcs::PolynomialCommitmentScheme;
use serde::{Deserialize, Serialize, de::DeserializeOwned};
use transcript::Transcript;

pub mod chunking;
pub mod claim;
pub mod context;
pub use context::ProverContext;
pub mod prover;
pub mod verifier;

/// Contains the additional data produced for each proving chunk, and needed by the verifier
#[derive(Clone, Serialize, Deserialize)]
#[serde(bound(serialize = "E: Serialize", deserialize = "E: DeserializeOwned"))]
pub(crate) struct ChunkProofData<E: ExtensionField, PCS: PolynomialCommitmentScheme<E>> {
    /// Commitments to the incoming and outgoing edges of the chunk
    commitments: ChunkIOCommitments<PCS::Commitment>,
    /// Evaluations of the polynomials corresponding to each port of the chunk's outgoing edges
    output_evals: BTreeMap<NodeOutput, PolynomialEvaluation<E>>,
    /// The chunk of the model this data refers to
    model_chunk: ModelChunk,
}

impl<E, PCS> Default for ChunkProofData<E, PCS>
where
    E: ExtensionField,
    PCS: PolynomialCommitmentScheme<E>,
{
    fn default() -> Self {
        Self {
            commitments: ChunkIOCommitments::default(),
            output_evals: BTreeMap::default(),
            model_chunk: ModelChunk::default(),
        }
    }
}

/// Contains all cryptographic material generated by the prover
#[derive(Clone, Serialize, Deserialize)]
#[serde(bound(serialize = "E: Serialize", deserialize = "E: DeserializeOwned"))]
pub struct Proof<E: ExtensionField, PCS: PolynomialCommitmentScheme<E>>
where
    E::BaseField: Serialize + DeserializeOwned,
{
    /// The successive sumchecks proofs. From output layer to input.
    steps: HashMap<NodeId, LayerProof<E, PCS>>,
    /// Proofs to merge output claims of a node, if any
    merge_claim_proofs: HashMap<NodeId, MergeClaimsProof<E>>,
    /// The proofs for any lookup tables used
    table_proofs: Vec<TableProof<E, PCS>>,
    /// the commitment proofs related to the weights
    commit: ModelOpeningProof<E, PCS>,
    // data about each proving chunk
    chunk_data: Vec<ChunkProofData<E, PCS>>,
}

#[derive(Clone, Serialize, Deserialize)]
#[serde(bound(serialize = "E: Serialize", deserialize = "E: DeserializeOwned"))]
pub struct TableProof<E: ExtensionField, PCS>
where
    PCS: PolynomialCommitmentScheme<E>,
    E::BaseField: Serialize + DeserializeOwned,
{
    /// The commitment to the multiplicity polynomial
    multiplicity_commit: PCS::Commitment,
    /// the lookup protocol proof for the table fractional sumcheck
    lookup: LogUpBatchProof<E>,
}

impl<E, PCS> TableProof<E, PCS>
where
    E: ExtensionField,
    PCS: PolynomialCommitmentScheme<E>,
    E::BaseField: Serialize + DeserializeOwned,
{
    /// gets a reference to the inner commitment
    pub fn get_commitment(&self) -> &PCS::Commitment {
        &self.multiplicity_commit
    }

    pub(crate) fn write_commitment<T: Transcript<E>>(
        &self,
        transcript: &mut T,
    ) -> anyhow::Result<()> {
        PCS::write_commitment(&self.multiplicity_commit, transcript)
            .map_err(|e| anyhow::anyhow!("{e:?}"))
    }
}
#[derive(Debug, Clone, Default)]
pub struct ChallengeStorage<E: ExtensionField> {
    /// This is the constant challenge looked in the lookup PIOPs
    pub constant_challenge: E,
    /// This is the map containing different values related to different tables/lookups
    pub challenge_map: HashMap<String, E>,
}

impl<E> ChallengeStorage<E>
where
    E: ExtensionField + Serialize + DeserializeOwned,
    E::BaseField: Serialize + DeserializeOwned,
{
    pub fn initialise<T: Transcript<E>>(ctx: &LookupContext, transcript: &mut T) -> Self {
        let constant_challenge = transcript
            .sample_and_append_challenge(b"table_constant")
            .elements;
        let challenge_map = ctx
            .iter()
            .map(|table_type| {
                let challenge = table_type.generate_challenge(transcript);

                (table_type.name(), challenge)
            })
            .collect::<HashMap<String, E>>();
        Self {
            constant_challenge,
            challenge_map,
        }
    }

    pub fn get_challenges_by_name(&self, name: &String) -> Option<(E, E)> {
        self.challenge_map
            .get(name)
            .map(|challenges| (self.constant_challenge, *challenges))
    }
}

pub(crate) fn compute_claim<E: ExtensionField, T: Transcript<E>>(
    transcript: &mut T,
    tensor: Tensor<E>,
) -> Claim<E> {
    // Derive the first randomness
    let r_i = transcript.read_challenges(tensor.num_vars());
    let y_i = tensor.into_mle().evaluate(&r_i);
    Claim {
        point: r_i,
        eval: y_i,
    }
}

#[cfg(test)]
mod test {
    use ff_ext::GoldilocksExt2;

    use crate::{
        default_transcript, init_test_logging, init_test_logging_default,
        iop::chunking::DefaultChunkingStrategy, model::Model, testing::Pcs,
    };

    use super::{prover::Prover, verifier::verify};

    type F = GoldilocksExt2;

    #[test]
    fn test_prover_steps_generic() {
        init_test_logging_default();
        use crate::StdRng;
        use ark_std::rand::SeedableRng;
        let mut rng = StdRng::seed_from_u64(4);
        let (model, input) = Model::random_with_rng(4, &mut rng).unwrap();

        model.describe();
        let trace = model.run(&input, &mut Default::default()).unwrap();
        let io = trace.to_verifier_io().unwrap();
        let (prover_ctx, verifier_ctx) = model
            .generate_contexts::<F, Pcs<F>>()
            .expect("unable to generate contexts");
        let mut prover_transcript = default_transcript();
        let prover = Prover::<_, _, _>::new(&prover_ctx, &mut prover_transcript);
        let proof = prover.prove(&trace).expect("unable to generate proof");
        let mut verifier_transcript = default_transcript();
        verify(&verifier_ctx, proof, io, &mut verifier_transcript).expect("invalid proof");
    }

    #[test]
    fn test_prover_steps_pooling() {
        init_test_logging_default();
        let (model, input) = Model::random_pooling(4).unwrap();
        model.describe();
        let trace = model.run(&input, &mut Default::default()).unwrap();
        let io = trace.to_verifier_io().unwrap();
        let (prover_ctx, verifier_ctx) = model
            .generate_contexts::<F, Pcs<F>>()
            .expect("unable to generate contexts");
        let mut prover_transcript = default_transcript();
        let prover = Prover::<_, _, _>::new(&prover_ctx, &mut prover_transcript);
        let proof = prover.prove(&trace).expect("unable to generate proof");
        let mut verifier_transcript = default_transcript();
        verify(&verifier_ctx, proof, io, &mut verifier_transcript).expect("invalid proof");
    }

    #[test]
    fn test_distribute_prove() {
        init_test_logging("debug");
        let num_dense_layers = 5;
        let (model, input) = Model::random(num_dense_layers).unwrap();
        model.describe();
        let trace = model.run(&input, &mut Default::default()).unwrap();
        let io = trace.to_verifier_io().unwrap();
        let (prover_ctx, verifier_ctx) = model
            .generate_contexts::<F, Pcs<F>>()
            .expect("unable to generate contexts");
        let mut prover_transcript = default_transcript();
        let prover = Prover::<_, _, _>::new(&prover_ctx, &mut prover_transcript);
        let proof = prover
            .distribute_prove(&trace, Some(3), DefaultChunkingStrategy::default())
            .expect("unable to generate proof");
        let mut verifier_transcript = default_transcript();
        verify(&verifier_ctx, proof, io, &mut verifier_transcript).expect("invalid proof");
    }
}
