use crate::{
    Claim, Tensor, VectorTranscript,
    commit::mmcs_context::ModelOpeningProof,
    graph::NodeId,
    iop::{context::VerifierContext, prover::MergeClaimsProof},
    layers::LayerProof,
    lookup::logup_gkr::structs::LogUpBatchProof,
};
use ff_ext::ExtensionField;
use mpcs::PolynomialCommitmentScheme;
use multilinear_extensions::mle::IntoMLE;
use serde::{Deserialize, Serialize, de::DeserializeOwned};
use std::collections::HashMap;
use transcript::Transcript;

pub mod claim;
pub mod context;
pub use context::ProverContext;
pub mod prover;
pub mod verifier;

/// Contains all cryptographic material generated by the prover
#[derive(Clone, Serialize, Deserialize)]
#[serde(bound(serialize = "E: Serialize", deserialize = "E: DeserializeOwned"))]
pub struct Proof<E: ExtensionField, PCS: PolynomialCommitmentScheme<E>>
where
    E::BaseField: Serialize + DeserializeOwned,
{
    /// The successive sumchecks proofs. From output layer to input.
    steps: HashMap<NodeId, LayerProof<E, PCS>>,
    /// Proofs to merge output claims of a node, if any
    merge_claim_proofs: HashMap<NodeId, MergeClaimsProof<E>>,
    /// The proofs for any lookup tables used
    table_proofs: Vec<TableProof<E, PCS>>,
    /// the commitment proofs related to the weights
    commit: ModelOpeningProof<E, PCS>,
}

#[derive(Clone, Serialize, Deserialize)]
#[serde(bound(serialize = "E: Serialize", deserialize = "E: DeserializeOwned"))]
pub struct TableProof<E: ExtensionField, PCS>
where
    PCS: PolynomialCommitmentScheme<E>,
    E::BaseField: Serialize + DeserializeOwned,
{
    /// The commitment to the multiplicity polynomial
    multiplicity_commit: PCS::Commitment,
    /// the lookup protocol proof for the table fractional sumcheck
    lookup: LogUpBatchProof<E>,
}

impl<E, PCS> TableProof<E, PCS>
where
    E: ExtensionField,
    PCS: PolynomialCommitmentScheme<E>,
    E::BaseField: Serialize + DeserializeOwned,
{
    /// gets a reference to the inner commitment
    pub fn get_commitment(&self) -> &PCS::Commitment {
        &self.multiplicity_commit
    }

    pub(crate) fn write_commitment<T: Transcript<E>>(
        &self,
        transcript: &mut T,
    ) -> anyhow::Result<()> {
        PCS::write_commitment(&self.multiplicity_commit, transcript)
            .map_err(|e| anyhow::anyhow!("{e:?}"))
    }
}
#[derive(Debug, Clone, Default)]
pub struct ChallengeStorage<E: ExtensionField> {
    /// This is the constant challenge looked in the lookup PIOPs
    pub constant_challenge: E,
    /// This is the map containing different values related to different tables/lookups
    pub challenge_map: HashMap<String, E>,
}

impl<E> ChallengeStorage<E>
where
    E: ExtensionField + Serialize + DeserializeOwned,
    E::BaseField: Serialize + DeserializeOwned,
{
    pub fn initialise<T: Transcript<E>, PCS: PolynomialCommitmentScheme<E>>(
        ctx: &VerifierContext<E, PCS>,
        transcript: &mut T,
    ) -> Self {
        let constant_challenge = transcript
            .sample_and_append_challenge(b"table_constant")
            .elements;
        let challenge_map = ctx
            .lookup
            .iter()
            .map(|table_type| {
                let challenge = table_type.generate_challenge(transcript);

                (table_type.name(), challenge)
            })
            .collect::<HashMap<String, E>>();
        Self {
            constant_challenge,
            challenge_map,
        }
    }

    pub fn get_challenges_by_name(&self, name: &String) -> Option<(E, E)> {
        self.challenge_map
            .get(name)
            .map(|challenges| (self.constant_challenge, *challenges))
    }
}

/// Computes the initial claims from the outputs of the model, since we prove in reverse
pub(crate) fn model_output_claims<'a, I, E: ExtensionField, T: Transcript<E>>(
    transcript: &mut T,
    outputs: I,
) -> Vec<Claim<E>>
where
    I: IntoIterator<Item = &'a Tensor<E>>,
{
    outputs
        .into_iter()
        .map(|out| {
            // Derive the first randomness
            let r_i = transcript.read_challenges(out.get_data().len().ilog2() as usize);
            // For the output, we manually evaluate the MLE and check if it's the same as what prover
            // gave. Note prover could ellude that but it's simpler to avoid that special check right
            // now.
            let output_mle = out.get_data().to_vec().into_mle();
            let computed_sum = output_mle.evaluate(&r_i);
            Claim {
                point: r_i,
                eval: computed_sum,
            }
        })
        .collect()
}

#[cfg(test)]
mod test {
    use ff_ext::GoldilocksExt2;

    use crate::{default_transcript, init_test_logging_default, model::Model, testing::Pcs};

    use super::{prover::Prover, verifier::verify};

    type F = GoldilocksExt2;

    #[test]
    fn test_prover_steps_generic() {
        init_test_logging_default();
        use crate::StdRng;
        use ark_std::rand::SeedableRng;
        let mut rng = StdRng::seed_from_u64(4);
        let (model, input) = Model::random_with_rng(4, &mut rng).unwrap();

        model.describe();
        let trace = model.run(&input, &mut Default::default()).unwrap();
        let io = trace.to_verifier_io().unwrap();
        let (prover_ctx, verifier_ctx) = model
            .generate_contexts::<F, Pcs<F>>()
            .expect("unable to generate contexts");
        let mut prover_transcript = default_transcript();
        let prover = Prover::<_, _, _>::new(&prover_ctx, &mut prover_transcript);
        let proof = prover.prove(&trace).expect("unable to generate proof");
        let mut verifier_transcript = default_transcript();
        verify::<_, _, _>(&verifier_ctx, proof, io, &mut verifier_transcript)
            .expect("invalid proof");
    }

    #[test]
    fn test_prover_steps_pooling() {
        init_test_logging_default();
        let (model, input) = Model::random_pooling(4).unwrap();
        model.describe();
        let trace = model.run(&input, &mut Default::default()).unwrap();
        let io = trace.to_verifier_io().unwrap();
        let (prover_ctx, verifier_ctx) = model
            .generate_contexts::<F, Pcs<F>>()
            .expect("unable to generate contexts");
        let mut prover_transcript = default_transcript();
        let prover = Prover::<_, _, _>::new(&prover_ctx, &mut prover_transcript);
        let proof = prover.prove(&trace).expect("unable to generate proof");
        let mut verifier_transcript = default_transcript();
        verify::<_, _, _>(&verifier_ctx, proof, io, &mut verifier_transcript)
            .expect("invalid proof");
    }
}
