use crate::{
    Claim, Tensor, VectorTranscript,
    graph::NodeOutput,
    iop::{chunking::ChunkIOCommitments, claim::PolynomialEvaluation},
    lookup::context::LookupContext,
};
use std::collections::{BTreeMap, HashMap};

use crate::{
    commit::mmcs_context::OpeningProof,
    graph::NodeId,
    iop::{chunking::ModelChunk, prover::MergeClaimsProof},
    layers::LayerProof,
    lookup::logup_gkr::structs::LogUpBatchProof,
};
use ff_ext::ExtensionField;
use mpcs::PolynomialCommitmentScheme;
use serde::{Deserialize, Serialize, de::DeserializeOwned};
use transcript::Transcript;

pub mod chunking;
pub mod claim;
pub mod context;
pub use context::ProverContext;
pub mod prover;
pub mod prover_graph;
pub mod verifier;

/// Contains the additional data produced for each proving chunk, and needed by the verifier
#[derive(Clone, Serialize, Deserialize)]
#[serde(bound(serialize = "E: Serialize", deserialize = "E: DeserializeOwned"))]
pub(crate) struct ChunkProofData<E: ExtensionField, PCS: PolynomialCommitmentScheme<E>> {
    /// Commitments to the incoming and outgoing edges of the chunk
    commitments: ChunkIOCommitments<PCS::Commitment>,
    /// Evaluations of the polynomials corresponding to each port of the chunk's outgoing edges
    output_evals: BTreeMap<NodeOutput, PolynomialEvaluation<E>>,
    /// The chunk of the model this data refers to
    model_chunk: ModelChunk,
}

impl<E, PCS> Default for ChunkProofData<E, PCS>
where
    E: ExtensionField,
    PCS: PolynomialCommitmentScheme<E>,
{
    fn default() -> Self {
        Self {
            commitments: ChunkIOCommitments::default(),
            output_evals: BTreeMap::default(),
            model_chunk: ModelChunk::default(),
        }
    }
}

/// All the cryptographic material generated by the prover for a given proven chunk
#[derive(Clone, Serialize, Deserialize)]
#[serde(bound(serialize = "E: Serialize", deserialize = "E: DeserializeOwned"))]
pub struct ChunkProof<E: ExtensionField, PCS: PolynomialCommitmentScheme<E>> {
    /// The successive sumchecks proofs. From output layer to input.
    steps: HashMap<NodeId, LayerProof<E, PCS>>,
    /// Proofs to merge output claims of a node, if any
    merge_claim_proofs: HashMap<NodeId, MergeClaimsProof<E>>,
    /// The proofs for any lookup tables used
    table_proof: Option<TableProof<E, PCS>>,
    /// the commitment proofs related to the witness polynomial of the chunk
    commit: OpeningProof<E, PCS>,
    // data about the proven chunk
    chunk_data: ChunkProofData<E, PCS>,
}

impl<E, PCS> std::fmt::Debug for ChunkProof<E, PCS>
where
    E: ExtensionField,
    PCS: mpcs::PolynomialCommitmentScheme<E>,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "ChunkProof {{ # steps: {:?}, # merge_claim_proofs: {:?}, table_proof ? {:?}, commit, chunk_data }}",
            self.steps.len(),
            self.merge_claim_proofs.len(),
            self.table_proof.is_some()
        )
    }
}

/// Contains all cryptographic material generated by the prover
#[derive(Clone, Serialize, Deserialize)]
#[serde(bound(serialize = "E: Serialize", deserialize = "E: DeserializeOwned"))]
pub struct Proof<E: ExtensionField, PCS: PolynomialCommitmentScheme<E>> {
    /// the proof for each proven chunk
    chunk_proofs: Vec<ChunkProof<E, PCS>>,
}

impl<E: ExtensionField, PCS: PolynomialCommitmentScheme<E>> std::fmt::Debug for Proof<E, PCS> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "Final Proof {{ # chunk_proofs: {:?}}}",
            self.chunk_proofs.len()
        )
    }
}

impl<E: ExtensionField, PCS: PolynomialCommitmentScheme<E>> From<Vec<ChunkProof<E, PCS>>>
    for Proof<E, PCS>
{
    fn from(chunk_proofs: Vec<ChunkProof<E, PCS>>) -> Self {
        Self { chunk_proofs }
    }
}

#[derive(Clone, Serialize, Deserialize)]
#[serde(bound(serialize = "E: Serialize", deserialize = "E: DeserializeOwned"))]
pub struct TableProof<E: ExtensionField, PCS>
where
    PCS: PolynomialCommitmentScheme<E>,
{
    /// The commitment to the multiplicity polynomial
    multiplicity_commit: PCS::Commitment,
    /// the lookup protocol proof for the table fractional sumcheck
    lookup: LogUpBatchProof<E>,
}

impl<E, PCS> TableProof<E, PCS>
where
    E: ExtensionField,
    PCS: PolynomialCommitmentScheme<E>,
{
    /// gets a reference to the inner commitment
    pub fn get_commitment(&self) -> &PCS::Commitment {
        &self.multiplicity_commit
    }

    pub(crate) fn write_commitment<T: Transcript<E>>(
        &self,
        transcript: &mut T,
    ) -> anyhow::Result<()> {
        PCS::write_commitment(&self.multiplicity_commit, transcript)
            .map_err(|e| anyhow::anyhow!("{e:?}"))
    }
}

#[derive(Debug, Clone, Default)]
pub struct ChallengeStorage<E: ExtensionField> {
    /// This is the constant challenge looked in the lookup PIOPs
    pub constant_challenge: E,
    /// This is the map containing different values related to different tables/lookups
    pub challenge_map: HashMap<String, E>,
}

impl<E> ChallengeStorage<E>
where
    E: ExtensionField,
{
    pub fn initialise<T: Transcript<E>>(ctx: &LookupContext, transcript: &mut T) -> Self {
        let constant_challenge = transcript
            .sample_and_append_challenge(b"table_constant")
            .elements;
        let challenge_map = ctx
            .iter()
            .map(|table_type| {
                let challenge = table_type.generate_challenge(transcript);

                (table_type.name(), challenge)
            })
            .collect::<HashMap<String, E>>();
        Self {
            constant_challenge,
            challenge_map,
        }
    }

    pub fn get_challenges_by_name(&self, name: &String) -> Option<(E, E)> {
        self.challenge_map
            .get(name)
            .map(|challenges| (self.constant_challenge, *challenges))
    }
}

pub(crate) fn compute_claim<E: ExtensionField, T: Transcript<E>>(
    transcript: &mut T,
    tensor: Tensor<E>,
) -> Claim<E> {
    // Derive the first randomness
    let r_i = transcript.read_challenges(tensor.num_vars());
    let y_i = tensor.into_mle().evaluate(&r_i);
    Claim {
        point: r_i,
        eval: y_i,
    }
}

#[cfg(test)]
mod test {
    use ff_ext::GoldilocksExt2;
    use transcript::BasicTranscript;

    use crate::{
        graph::executor::ThreadPoolExecutor, init_test_logging, init_test_logging_default,
        iop::chunking::DefaultChunkingStrategy, model::Model, testing::Pcs,
    };

    use super::{prover::Prover, verifier::verify};

    type F = GoldilocksExt2;

    type T = BasicTranscript<F>;
    type P<'a, 'b> = Prover<'a, 'b, F, BasicTranscript<F>, Pcs<F>>;

    #[test]
    fn test_prover_steps_generic() {
        init_test_logging_default();
        use crate::StdRng;
        use ark_std::rand::SeedableRng;
        let mut rng = StdRng::seed_from_u64(4);
        let (model, input) = Model::random_with_rng(4, &mut rng).unwrap();

        model.describe();
        let trace = model.run(input, &mut Default::default()).unwrap();
        let io = trace.to_verifier_io().unwrap();
        let (prover_ctx, verifier_ctx) = model
            .generate_contexts::<F, Pcs<F>>()
            .expect("unable to generate contexts");
        let proof = P::prove(&prover_ctx, trace, &model).expect("unable to generate proof");
        verify::<_, T, _>(&verifier_ctx, proof, io).expect("invalid proof");
    }

    #[test]
    fn test_prover_steps_pooling() {
        init_test_logging_default();
        let (model, input) = Model::random_pooling(4).unwrap();
        model.describe();
        let trace = model.run(input, &mut Default::default()).unwrap();
        let io = trace.to_verifier_io().unwrap();
        let (prover_ctx, verifier_ctx) = model
            .generate_contexts::<F, Pcs<F>>()
            .expect("unable to generate contexts");
        let proof = P::prove(&prover_ctx, trace, &model).expect("unable to generate proof");
        verify::<_, T, _>(&verifier_ctx, proof, io).expect("invalid proof");
    }

    #[test]
    fn test_distribute_prove() {
        init_test_logging("debug");
        let num_dense_layers = 5;
        let (model, inputs) = Model::random(num_dense_layers).unwrap();
        model.describe();
        let trace = model.run(inputs, &mut Default::default()).unwrap();
        let io = trace.to_verifier_io().unwrap();
        let (prover_ctx, verifier_ctx) = model
            .generate_contexts::<F, Pcs<F>>()
            .expect("unable to generate contexts");
        let proof = P::chunked_prove_local::<_, ThreadPoolExecutor>(
            &prover_ctx,
            trace,
            Some(3),
            DefaultChunkingStrategy::default(),
            &model,
            (),
        )
        .expect("unable to generate proof");
        verify::<_, T, _>(&verifier_ctx, proof, io).expect("invalid proof");
    }
}
