[package]
name = "remote-store"
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[[bin]]
name = "deep-prove-store"
path = "src/bin/store/main.rs"

[dependencies]
io-copy.workspace = true

anyhow.workspace = true
clap = { workspace = true, features = ["cargo", "derive", "env"] }
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "macros", "net", "sync", "tracing"] }
tokio-metrics.workspace = true
tracing.workspace = true
uuid = { workspace = true, features = ["serde"] }
vise.workspace = true
