[package]
name = "utils"
description = "various utils"
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
mem-track = ["dep:mem-track", "dep:flate2"]

[dependencies]
anyhow = { workspace = true }
bytesize = { version = "2.0.1" }
csv = { workspace = true }
flate2 = { version = "1.1.2", optional = true }
mem-track = { git = "https://github.com/hackaugusto/mem-track", branch = "main", optional = true }
memory-stats = { version = "1.2.0" }
thiserror = { workspace = true }
thousands = { version = "0.2.0" }
tracing = { workspace = true }
