[package]
name = "utils"
description = "various utils"
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
mem-track = ["dep:mem-track"]

[dependencies]
anyhow.workspace = true
bytesize = "2.0.1"
csv.workspace = true
flate2 = "1.1.2"
mem-track = { git = "https://github.com/hackaugusto/mem-track", branch = "main", optional = true }
memory-stats = { version = "1.2.0" }
thiserror.workspace = true
thousands = "0.2.0"
tracing = { workspace = true }
