[package]
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "zkml"
description = "ZKML library"
readme.workspace = true
repository.workspace = true
version.workspace = true

[package.metadata.cargo-machete]
ignored = ["prost"]

[[bin]]
name = "bench"
path = "src/bin/bench.rs"

[features]
blake = ["mpcs/blake"]
default = ["cpu"]
# Capture layers' quatization outputs for regression tests
capture-layers-quant = ["dep:sha2"]
cpu = ["burn/ndarray"]
gpu = ["burn/wgpu", "dep:cubecl", "dep:burn-cubecl"]
mem-track = ["utils/mem-track"]

[dependencies]
anyhow.workspace = true
ark-std.workspace = true
average = { version = "0.16.0", features = ["std"] }
burn = { version = "0.18.0", default-features = false }
burn-cubecl = { version = "0.18.0", default-features = false, optional = true }
candle-core = "0.9.1"
clap = { workspace = true, features = ["derive", "env"] }
cubecl = { version = "0.6.0", default-features = false, features = [
  "wgpu-msl",
], optional = true }
derive_more = { workspace = true, features = ["full"] }
either = { workspace = true }
ff_ext = { workspace = true }
gguf-rs = "0.1.4"
hex = { workspace = true }
itertools.workspace = true
mpcs = { workspace = true }
multilinear_extensions = { workspace = true, features = ["parallel"] }
p3-field = { workspace = true }
p3-goldilocks = { workspace = true }
prost = { version = "0.13.3" }
prost-tract-compat = { package = "prost", version = "0.11.9" }
rayon.workspace = true
rmp-serde = { workspace = true }
rust_tokenizers = "8.1.1"
serde.workspace = true
serde_json.workspace = true
sha2 = { version = "0.10.9", optional = true }
sumcheck.workspace = true
tenstore = { path = "../tenstore" }
timed = { workspace = true }
timed-core = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
  "env-filter",
  "fmt",
  "json",
] }
tract-onnx = { workspace = true }
transcript = { workspace = true }
utils = { path = "../utils" }


[dev-dependencies]
criterion = { "version" = "0.6", features = ["html_reports"] }
ndarray = "0.16.1"
proptest = "1.7.0"
rstest = "0.25.0"
sha2 = "0.10.9"
tempfile.workspace = true
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }
wreq = "5"
wreq-util = "2"
zstd = "0.13.3"

[[bench]]
harness = false
name = "prove-model"

[[bench]]
harness = false
name = "gpu"

[lints.clippy]
dbg_macro = "deny"
print_stderr = "deny"
print_stdout = "deny"
