name: Docker

on:
  push:
    branches: [master]
    tags: ['**']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  docker:
    uses: Lagrange-Labs/github-workflows/.github/workflows/docker-matrix-build.yml@main
    with:
      path-filters: |
        deep-prove-worker:
          - 'zkml/**'
          - 'deep-prove/**'
          - 'mpcs/**'
          - 'docker/deep-prove-worker.dockerfile'
          - '.github/workflows/docker.yml'
        deep-prove-aws-client:
          - 'zkml/**'
          - 'deep-prove/**'
          - 'mpcs/**'
          - 'docker/deep-prove-aws-client.dockerfile'
          - '.github/workflows/docker.yml'
        deep-prove-aws-worker:
          - 'zkml/**'
          - 'deep-prove/**'
          - 'mpcs/**'
          - 'docker/deep-prove-aws-worker.dockerfile'
          - '.github/workflows/docker.yml'
      all-images: '["deep-prove-worker", "deep-prove-aws-client", "deep-prove-aws-worker"]'
      dockerfile-pattern: 'docker/{image}.dockerfile'
      default-branch: master
      build-runner: arc-runner-ccx43
      checkout-submodules: recursive
      save-artifact: true
    secrets: inherit
