name: "Rust GPU tests"
permissions:
  contents: read

on:
  push:
    tags:
      - '**'
    branches:
      - master
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: gpu-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Check for changes in zkML sources
    runs-on: arc-runner-cpx22
    permissions:
      pull-requests: read
      contents: read
    outputs:
      should_run: ${{ steps.filter.outputs.watches }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            watches:
              - 'zkml/**'
              - '.github/workflows/gpu-tests.yml'
              - 'rust-toolchain.toml'

  test:
    name: GPU Tests
    needs: changes
    # Runs on:
    # - PRs if path filter passes and PR is not draft
    # - on master and tag push always
    if: |
        (github.event_name == 'pull_request'
          && needs.changes.outputs.should_run == 'true'
          && github.event.pull_request.draft == false
          && github.event.pull_request.head.repo.full_name == github.repository)
        || github.event_name == 'push'

    runs-on: ['gpu']
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Sanity check
        run: [ -f $HOME/.gitconfig ] && echo "Removing gitconfig" && rm ${HOME}/.gitconfig || exit 0

      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Force-check LFS
        run: git lfs pull

      - name: Set RNG seed
        run: |
          seed="$(date +%s)"
          echo RNG seed: "$seed"
          echo RNG_SEED="$seed" >> "$GITHUB_ENV"

      - name: Run concurrent GPU tests
        shell: devenv shell bash -- -e {0}
        # Run with retries because the tests run concurrently racing for VRAM.
        # When the VRAM is full some tests might fail with `BufferTooBig` error,
        # but pass when ran on their own. Running tests sequentially is
        # significantly slower.
        #
        # Skipping `test_gpt2_replace` as it doesn't pass due to precision loss
        # on GPU. This not important as this is a one of conversion that can run
        # on CPU.
        #
        # `LD_LIBRARY_PATH` is appended with path to pre-installed CUDA libs.
        # The required libs are copied into `cuda`, because linking the whole
        # /usr/lib messes up devenv
        run: |
          mkdir -p $HOME/cuda
          cp /usr/lib/x86_64-linux-gnu/libcuda.so $HOME/cuda
          cd zkml
          LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/cuda:/usr/local/cuda/targets/x86_64-linux/lib:/usr/local/cuda/lib64" \
          CUDARC_CUDA_VERSION="13000" \
          cargo nextest run --features cuda --retries 2 -- \
            --skip model::transform::impls::gpt2rmsnorm::tests::test_gpt2_replace \
            --skip parser::llm::models::gemma3::safe_tests::test_safe_gemma3_load_model \
            --skip parser::llm::models::gemma3::tests::test_gguf_gemma3_load_model \
            --skip parser::llm::models::gemma3::tests::test_gguf_gemma3_logits \
            --skip parser::llm::models::gemma3::tests::test_safe_gemma3_intermediates \
            --skip layers::einsum::evaluate::tests::test_cached_qkv \
            --skip model::transform::impls::gpt2rmsnorm::tests::test_mean_subtracted_tensor \
            --skip model::llm::test::test_llm_driver_int_inference_gemma3 \
            --skip parser::llm::models::gpt2::tests::test_safe_gpt2_load_model
        env:
          IN_CI: "true"

      - name: Run sequential GPU tests
        shell: devenv shell bash -- -e {0}
        # Tests that take more VRAM run sequentially to avoid `BufferTooBig` errors
        run: |
          cd zkml
          LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/cuda:/usr/local/cuda/targets/x86_64-linux/lib:/usr/local/cuda/lib64" \
          CUDARC_CUDA_VERSION="13000" \
          cargo nextest run --features cuda --test-threads 1 -- \
            parser::llm::models::gemma3::safe_tests::test_safe_gemma3_load_model \
            parser::llm::models::gemma3::tests::test_gguf_gemma3_load_model \
            model::llm::test::test_llm_driver_int_inference_gemma3 \
            parser::llm::models::gpt2::tests::test_safe_gpt2_load_model
        env:
          IN_CI: "true"
