name: "Main branch Bench"

on:
  push:
    branches: master

jobs:
  changes:
    runs-on: ["nix"]
    outputs:
      should_run: ${{ steps.filter.outputs.watches }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            watches:
              - 'zkml/**'
              - 'mpcs/**'
              - '.github/workflows/main-bench.yml'

  cpu_benchmark_master_branch:
    name: Master CPU Benchmarking
    needs: changes
    if: ${{ needs.changes.outputs.should_run == 'true' }}
    permissions:
      checks: write
      contents: read
      id-token: write
    runs-on: ['arc-runner-ccx63']
    steps:
      - name: Setup sccache
        uses: Lagrange-Labs/github-workflows/.github/actions/setup-sccache@main

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xz-utils git-lfs
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Install devenv
        run: |
          nix profile install nixpkgs#devenv --accept-flake-config
      - name: Sanity check
        if: always()
        run: |
          [ -f $HOME/.gitconfig ] && echo "Removing gitconfig" && rm ${HOME}/.gitconfig || exit 0

      - uses: actions/checkout@v4
        with:
          clean: "false"
          submodules: "recursive"

      - name: Install bencher bin
        shell: devenv shell bash -- -e {0}
        run: cargo install --git https://github.com/bencherdev/bencher --tag v0.5.7 --locked bencher_cli --debug

      - name: Track PR Benchmarks with Bencher
        shell: devenv shell bash -- -e {0}
        run: |
          cd zkml && \
          bencher run \
          --host https://api.bencher.dev \
          --project deep-prove-private-70c58ed-ejzl400nndqc0 \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch master \
          --threshold-measure latency \
          --threshold-test percentage \
          --threshold-upper-boundary 0.20 \
          --threshold-max-sample-size 15 \
          --thresholds-reset \
          --testbed ci-runner \
          --err \
          --adapter rust_criterion \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          "cargo bench --bench prove-model"

      - name: Show sccache stats
        run: sccache --show-stats

  gpu_benchmark_master_branch:
    name: Master GPU Benchmarking
    needs: changes
    if: ${{ needs.changes.outputs.should_run == 'true' }}
    permissions:
      checks: write
      contents: read
      id-token: write
    runs-on: ['gpu']
    steps:
      - name: Setup sccache
        uses: Lagrange-Labs/github-workflows/.github/actions/setup-sccache@main

      - name: Sanity check
        if: always()
        run: |
          [ -f $HOME/.gitconfig ] && echo "Removing gitconfig" && rm ${HOME}/.gitconfig || exit 0

      - uses: actions/checkout@v4
        with:
          clean: "false"
          submodules: "recursive"

      - name: Install bencher bin
        shell: devenv shell bash -- -e {0}
        run: cargo install --git https://github.com/bencherdev/bencher --tag v0.5.7 --locked bencher_cli --debug

      - name: Track PR Benchmarks with Bencher
        shell: devenv shell bash -- -e {0}
        # `LD_LIBRARY_PATH` is appended with path to pre-installed CUDA libs.
        # The required libs are copied into `cuda`, because linking the whole
        # /usr/lib messes up devenv
        run: |
          mkdir -p $HOME/cuda
          cp /usr/lib/x86_64-linux-gnu/libcuda.so $HOME/cuda
          cd zkml
          LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/cuda:/usr/local/cuda/targets/x86_64-linux/lib:/usr/local/cuda/lib64" \
          CUDARC_CUDA_VERSION="13000" \
          bencher run \
          --host https://api.bencher.dev \
          --project deep-prove-private-70c58ed-ejzl400nndqc0 \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch master \
          --threshold-measure latency \
          --threshold-test percentage \
          --threshold-upper-boundary 0.20 \
          --threshold-max-sample-size 15 \
          --thresholds-reset \
          --testbed ci-gpu-runner \
          --err \
          --adapter rust_criterion \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          "cargo bench --bench prove-model --features cuda -- inference"

      - name: Show sccache stats
        run: sccache --show-stats
