name: "Main branch Bench"

on:
  push:
    branches: master

jobs:
  changes:
    runs-on: ["nix"]
    outputs:
      should_run: ${{ steps.filter.outputs.watches }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            watches:
              - 'zkml/**'
              - 'mpcs/**'
              - '.github/workflows/main-bench.yml'

  benchmark_pr_branch:
    name: Master Benchmarking
    needs: changes
    if: ${{ needs.changes.outputs.should_run == 'true' }}
    permissions:
      checks: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: "false"
          submodules: "recursive"
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          # Manually configure rust-cache
          cache: false
      - uses: bencherdev/bencher@main
        shell: devenv shell bash -- -e {0}
        run: |
          cd zkml && \
          bencher run \
          --project deep-prove-private-70c58ed-ejzl400nndqc0 \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch master \
          --threshold-measure latency \
          --threshold-test percentage \
          --threshold-upper-boundary 0.20 \
          --thresholds-reset \
          --testbed ci-runner \
          --err \
          --adapter rust_criterion \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          "cargo bench --bench prove-model"
