name: "PR Bench"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: bench-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ['nix']
    permissions:
      pull-requests: read
    outputs:
      should_run: ${{ steps.filter.outputs.watches }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            watches:
              - 'zkml/**'
              - 'mpcs/**'
              - '.github/workflows/pr-bench.yml'

  benchmark_pr_branch:
    name: PR Benchmarking
    needs: changes
    # DO NOT REMOVE: For handling Fork PRs see Pull Requests from Forks
    if: |
      needs.changes.outputs.should_run == 'true'
        && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: "false"
          lfs: 'true'
          submodules: "recursive"

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            zkml_src:
              - 'zkml/**'
              - '.github/workflows/pr-bench.yml'

      - uses: bencherdev/bencher@main
        shell: devenv shell bash -- -e {0}
        run: |
          cd zkml && \
          bencher run \
          --project deep-prove-private-70c58ed-ejzl400nndqc0 \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch "$GITHUB_HEAD_REF" \
          --start-point master \
          --start-point-clone-thresholds \
          --start-point-reset \
          --testbed ci-runner \
          --err \
          --adapter rust_criterion \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          "cargo bench --bench prove-model"
