name: "Rust tests & lint"
permissions:
  contents: read

on:
  push:
    tags:
      - '**'
    branches:
      - master
  pull_request:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Check for changes in zkML sources
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      zkml_src: ${{ steps.filter.outputs.zkml_src }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            zkml_src:
              - 'zkml/**'
              - 'mpcs/**'
              - '.github/workflows/tests.yml'
              - 'rust-toolchain.toml'

  test:
    name: Tests
    needs: changes
    if: ${{ needs.changes.outputs.zkml_src != '[]' }}
    runs-on: ['nix']
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: "true"
          submodules: "recursive"

      - name: Force-check LFS
        run: git lfs pull

      - name: Set RNG seed
        run: |
          seed="$(date +%s)"
          echo RNG seed: "$seed"
          echo RNG_SEED="$seed" >> "$GITHUB_ENV"

      - name: Run cargo check
        shell: devenv shell bash -- -e {0}
        run: cargo check -p zkml --all --tests --benches
        env:
          RUSTFLAGS: "-W warnings"

      - name: Run cargo test
        run: devenv test


  linting:
    needs: changes
    runs-on: ['nix']
    if: ${{ needs.changes.outputs.zkml_src != '[]' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          clean: "false"

      - name: Clippy
        shell: devenv shell bash -- -e {0}
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Rust Format
        shell: devenv shell bash -- -e {0}
        run: cargo fmt --all
